### ISSUE TITLE
deadlock during load testing

### ISSUE THREAD

**Issue by pciet** [pciet/wichess#45]
Via http://{{addr}}/debug/pprof/goroutine?debug=2: https://gist.github.com/pciet/6874c1af77eb41e9f135de2e29332389

Here's the load test debug output excerpt up to the deadlock: https://gist.github.com/pciet/37b16e06ac41cfbe959c2fe6ba217a05

After 600 games without pprof and after 300 games with pprof the load test stops making new calls.

The server has not made any output even though debug is on.

This is with the go 1.10 beta1 but I've seen this once before with previous go versions. There may be a race condition in the database transactions that is only appearing more frequently because request time has been significantly reduced by https://github.com/pciet/wichess/commit/89c55b108eee0d4067119ec7995321e47c5d87e5

**Comment by pciet** [comment]
From /var/log/postgresql/postgresql-9.5-main.log on the server "unexpected EOF" repeated many times:

```
...
2017-12-07 20:26:36 CST [6553-1] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6495-1] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6555-1] test@test LOG:  could not receive data from client: Connection reset by peer
2017-12-07 20:26:36 CST [6555-2] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6550-1] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6504-1] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6503-1] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6549-1] test@test LOG:  unexpected EOF on client connection with an open transaction
2017-12-07 20:26:36 CST [6502-1] test@test LOG:  unexpected EOF on client connection with an open transaction
```

**Comment by pciet** [comment]
Many goroutines are blocking on semaphore acquire, gameMonitorsLock is r-acquired here:

```
goroutine 1202020 [chan send, 695 minutes]:
main.game.promote.func1(0xc422249000)
	/home/pciet/go/src/github.com/pciet/wichess/game_moving.go:224 +0xc5
created by main.game.promote
	/home/pciet/go/src/github.com/pciet/wichess/game_moving.go:220 +0x676
```

```
	go func() {
		gameMonitorsLock.RLock()
		c, has := gameMonitors[g.ID]
		if has {
			c.move <- time.Now() // blocking on send
		}
		gameMonitorsLock.RUnlock()
	}()
```

**Comment by pciet** [comment]
Many goroutines are blocked on making the database connection when opening a transaction:

```
goroutine 1122181 [select, 683 minutes]:
database/sql.(*DB).conn(0xc420092c80, 0x892580, 0xc4200120e0, 0x1, 0x301, 0x0, 0x302)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:1063 +0x62d
database/sql.(*DB).begin(0xc420092c80, 0x892580, 0xc4200120e0, 0x0, 0x301, 0xc4224ddd40, 0x400, 0x0)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:1566 +0x4f
database/sql.(*DB).BeginTx(0xc420092c80, 0x892580, 0xc4200120e0, 0x0, 0x406, 0xc4224ddda0, 0x407)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:1548 +0x8a
database/sql.(*DB).Begin(0xc420092c80, 0x501, 0xc4224dde00, 0x502)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:1562 +0x4c
main.DB.Begin(0xc420092c80, 0x0)
	/home/pciet/go/src/github.com/pciet/wichess/database.go:34 +0x2b
main.DB.updateGameTimes(0xc420092c80, 0x117, 0xd18c2e2800, 0xc420acb218, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pciet/go/src/github.com/pciet/wichess/game_time.go:90 +0x87
main.listeningToGame.func1(0xc4208b9dc8, 0x7, 0xc42006f080, 0xc42006f140, 0x117, 0xd18c2e2800, 0x1a978a78, 0xed1bbf6b3, 0xc42042ec60)
	/home/pciet/go/src/github.com/pciet/wichess/game_listening.go:71 +0x455
created by main.listeningToGame
	/home/pciet/go/src/github.com/pciet/wichess/game_listening.go:44 +0x52d
```

**Comment by pciet** [comment]
Both gameListeningLock and gameMonitorsLock are acquired and blocking goroutines indefinitely.

**Comment by pciet** [comment]
The test is configured for 80 clients and the server is set to max 50 open database connections and 10 idle connections. Trying again with 100 max open database connections.

**Comment by pciet** [comment]
database/sql manages the number of connections and puts over-max connection requests into a queue:

```
// conn returns a newly-opened or cached *driverConn.
func (db *DB) conn(strategy connReuseStrategy) (*driverConn, error) {
...
	// Out of free connections or we were asked not to use one.  If we're not
	// allowed to open any more connections, make a request and wait.
	if db.maxOpen > 0 && db.numOpen >= db.maxOpen {
		// Make the connRequest channel. It's buffered so that the
		// connectionOpener doesn't block while waiting for the req to be read.
		req := make(chan connRequest, 1)
		db.connRequests = append(db.connRequests, req)
		db.mu.Unlock()
		ret, ok := <-req
		if !ok {
			return nil, errDBClosed
		}
		if ret.err == nil && ret.conn.expired(lifetime) {
			ret.conn.Close()
			return nil, driver.ErrBadConn
		}
		return ret.conn, ret.err
	}
...
```

**Comment by pciet** [comment]
Still seen with max open connections set to 100 for the wichess server: https://gist.github.com/pciet/4edd4f21d238a24165af65f8dfc29e6c

**Comment by pciet** [comment]
A few minutes after the deadlock I'm not seeing those /var/log/postgres messages, those may be timeouts after the deadlock lasts for awhile.

**Comment by pciet** [comment]
This goroutine is waiting for a response from postgres. I'd guess that another transaction (FOR UPDATE) that locked up has blocked this transaction in postgres.

```
goroutine 512 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fd3a857cfd0, 0x72, 0xc42161e100)
	/home/pciet/sdk/go1.10beta1/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420cf2298, 0x72, 0xffffffffffffff00, 0x88fb80, 0xa436d0)
	/home/pciet/sdk/go1.10beta1/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420cf2298, 0xc42074b000, 0x1000, 0x1000)
	/home/pciet/sdk/go1.10beta1/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420cf2280, 0xc42074b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/pciet/sdk/go1.10beta1/src/internal/poll/fd_unix.go:135 +0x17d
net.(*netFD).Read(0xc420cf2280, 0xc42074b000, 0x1000, 0x1000, 0xc42161e218, 0x434b9c, 0x200)
	/home/pciet/sdk/go1.10beta1/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc420186280, 0xc42074b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/pciet/sdk/go1.10beta1/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc422424480, 0xc42248bba0, 0x5, 0x200, 0x42bd04, 0x856988, 0xc42161e2f0)
	/home/pciet/sdk/go1.10beta1/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x88e6c0, 0xc422424480, 0xc42248bba0, 0x5, 0x200, 0x5, 0x4120fd, 0xc4207ef6c0, 0x20)
	/home/pciet/sdk/go1.10beta1/src/io/io.go:309 +0x86
io.ReadFull(0x88e6c0, 0xc422424480, 0xc42248bba0, 0x5, 0x200, 0x0, 0xc420150000, 0xcb)
	/home/pciet/sdk/go1.10beta1/src/io/io.go:327 +0x58
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).recvMessage(0xc42248bb80, 0xc4207ef6c0, 0x79c860, 0x11, 0x18)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:947 +0xf3
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).recv1Buf(0xc42248bb80, 0xc4207ef6c0, 0xa)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:997 +0x39
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).recv1(0xc42248bb80, 0xc420186280, 0xc42248bba0)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:1018 +0x7c
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).readBindResponse(0xc42248bb80)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:1633 +0x2f
github.com/pciet/wichess/vendor/github.com/lib/pq.(*stmt).exec(0xc42020e1e0, 0xc420164c70, 0x1, 0x1)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:1270 +0x823
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).query(0xc42248bb80, 0xc4208f3920, 0x30, 0xc420164c70, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:855 +0x2a1
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).QueryContext(0xc42248bb80, 0x892580, 0xc4200120e0, 0xc4208f3920, 0x30, 0xc4222a3050, 0x1, 0x1, 0x0, 0x3, ...)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn_go18.go:21 +0x1c8
database/sql.ctxDriverQuery(0x892580, 0xc4200120e0, 0x7fd3a8549208, 0xc42248bb80, 0x0, 0x0, 0xc4208f3920, 0x30, 0xc4222a3050, 0x1, ...)
	/home/pciet/sdk/go1.10beta1/src/database/sql/ctxutil.go:48 +0x235
database/sql.(*DB).queryDC.func1()
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:1464 +0x1c5
database/sql.withLock(0x8903e0, 0xc420fa0f80, 0xc42161e9b0)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:3032 +0x63
database/sql.(*DB).queryDC(0xc4201b0000, 0x892580, 0xc4200120e0, 0x892540, 0xc4220a4580, 0xc420fa0f80, 0xc420164c60, 0xc4208f3920, 0x30, 0xc4216209e8, ...)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:1459 +0x5e9
database/sql.(*Tx).QueryContext(0xc420ef2580, 0x892580, 0xc4200120e0, 0xc4208f3920, 0x30, 0xc4216209e8, 0x1, 0x1, 0x30, 0x1, ...)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:2128 +0x113
database/sql.(*Tx).QueryRowContext(0xc420ef2580, 0x892580, 0xc4200120e0, 0xc4208f3920, 0x30, 0xc4216209e8, 0x1, 0x1, 0x30)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:2143 +0x8d
database/sql.(*Tx).QueryRow(0xc420ef2580, 0xc4208f3920, 0x30, 0xc4216209e8, 0x1, 0x1, 0x1)
	/home/pciet/sdk/go1.10beta1/src/database/sql/sql.go:2154 +0x7c
main.TX.gameWithIdentifier(0xc420ef2580, 0xdc, 0xc420ef2501, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pciet/go/src/github.com/pciet/wichess/game.go:122 +0x190
main.acknowledgeGameCompletionHandler(0x892240, 0xc421980380, 0xc42077ed00)
	/home/pciet/go/src/github.com/pciet/wichess/web_acknowledge.go:61 +0x2ff
net/http.HandlerFunc.ServeHTTP(0x8569d0, 0x892240, 0xc421980380, 0xc42077ed00)
	/home/pciet/sdk/go1.10beta1/src/net/http/server.go:1939 +0x44
net/http.(*ServeMux).ServeHTTP(0xa81be0, 0x892240, 0xc421980380, 0xc42077ed00)
	/home/pciet/sdk/go1.10beta1/src/net/http/server.go:2316 +0x130
net/http.serverHandler.ServeHTTP(0xc420192750, 0x892240, 0xc421980380, 0xc42077ed00)
	/home/pciet/sdk/go1.10beta1/src/net/http/server.go:2665 +0xbc
net/http.(*conn).serve(0xc420385a40, 0x892540, 0xc42018e280)
	/home/pciet/sdk/go1.10beta1/src/net/http/server.go:1822 +0x648
created by net/http.(*Server).Serve
	/home/pciet/sdk/go1.10beta1/src/net/http/server.go:2766 +0x27b
```

**Comment by pciet** [comment]
Again the only chan send:

```
goroutine 1042770 [chan send, 1 minutes]:
main.game.move.func1(0xc420937000)
	/home/pciet/go/src/github.com/pciet/wichess/game_moving.go:107 +0xc5
created by main.game.move
	/home/pciet/go/src/github.com/pciet/wichess/game_moving.go:103 +0x9ca
```

Same pattern but in the move function instead of the promote function:

```
	go func() {
		gameMonitorsLock.RLock()
		c, has := gameMonitors[g.ID]
		if has {
			c.move <- time.Now() // this is what locks it all up probably
		}
		gameMonitorsLock.RUnlock()
	}()
```

**Comment by pciet** [comment]
This looks to be a deadlock caused by a race between notifying a move is made and handling game completion because of a time loss. Not seen after 1000 games with https://github.com/pciet/wichess/commit/bd4332577a471b5934cbca742167d1884f0545d9
