### ISSUE TITLE
crash: too many open files

### ISSUE THREAD

**Issue by pciet** [pciet/wichess#5]
> 2017/10/29 14:52:02 http: panic serving [::1]:62473: failed to parse web/html/game.html: open web/html/game.html: too many open files
goroutine 9353 [running]:
net/http.(*conn).serve.func1(0xc420224780)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1382500, 0xc420356590)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc420526140, 0x50)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:50 +0x63
main.executeWebTemplate(0x15bef60, 0xc4202d0380, 0x1414844, 0x12, 0x13d9da0, 0xc42000aa00)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web.go:36 +0x375
main.easyComputerHandler(0x15bef60, 0xc4202d0380, 0xc420124400)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_easycomputer.go:73 +0x269
net/http.HandlerFunc.ServeHTTP(0x1426db0, 0x15bef60, 0xc4202d0380, 0xc420124400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x15f0900, 0x15bef60, 0xc4202d0380, 0xc420124400)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200aec60, 0x15bef60, 0xc4202d0380, 0xc420124400)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420224780, 0x15bf5a0, 0xc42051f640)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/10/29 14:52:06 http: panic serving [::1]:62474: failed to parse web/html/game.html: open web/html/game.html: too many open files
goroutine 9355 [running]:
net/http.(*conn).serve.func1(0xc420224960)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1382500, 0xc4203c8d70)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc4204d0230, 0x50)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:50 +0x63
main.executeWebTemplate(0x15bef60, 0xc4202d0460, 0x1414844, 0x12, 0x13d9da0, 0xc420124600)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web.go:36 +0x375
main.easyComputerHandler(0x15bef60, 0xc4202d0460, 0xc420124500)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_easycomputer.go:73 +0x269
net/http.HandlerFunc.ServeHTTP(0x1426db0, 0x15bef60, 0xc4202d0460, 0xc420124500)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x15f0900, 0x15bef60, 0xc4202d0460, 0xc420124500)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200aec60, 0x15bef60, 0xc4202d0460, 0xc420124500)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420224960, 0x15bf5a0, 0xc42051f840)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/10/29 14:52:11 http: panic serving [::1]:62475: failed to parse web/html/game.html: open web/html/game.html: too many open files
goroutine 9336 [running]:
net/http.(*conn).serve.func1(0xc42020a0a0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1382500, 0xc4203c8f20)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc4204d02d0, 0x50)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:50 +0x63
main.executeWebTemplate(0x15bef60, 0xc4204e2000, 0x1414844, 0x12, 0x13d9da0, 0xc420124700)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web.go:36 +0x375
main.easyComputerHandler(0x15bef60, 0xc4204e2000, 0xc42000ab00)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_easycomputer.go:73 +0x269
net/http.HandlerFunc.ServeHTTP(0x1426db0, 0x15bef60, 0xc4204e2000, 0xc42000ab00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x15f0900, 0x15bef60, 0xc4204e2000, 0xc42000ab00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200aec60, 0x15bef60, 0xc4204e2000, 0xc42000ab00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42020a0a0, 0x15bf5a0, 0xc420418e80)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by pciet** [comment]
Fixed in https://github.com/pciet/wichess/commit/ad44525846d204bd465f2d7f03b8d7c5776161aa
