### ISSUE TITLE
deadlock in load testing

### ISSUE THREAD

**Issue by pciet** [pciet/wichess#52]
During load testing after about 3k games a deadlock occurs: https://gist.github.com/pciet/f395696be42c3c9d6bcdaf71c7708657

A deadlock occured after about 7k games where pprof wasn't included previously.

Both send (move notification holding gameMonitorsLock.RLock) and receive (waiting for diff to send to player) channel operations are blocking, gameMonitorsLock.Lock is blocking for a new game starting, and gameListeningLock.RLock is blocking.

Manually loading index hangs (the pprof stack trace above is after this is tried) because a transaction in database.validSession(r) blocks. A session for that key had already been opened hours earlier.

**Comment by pciet** [comment]
This is with go 1.10 beta 2. Previously with go 1.8.5 over 50k games were played with the load test. The Ubuntu server did have packages updated.

**Comment by pciet** [comment]
About 66 goroutines waiting for a diff via ```<-listenTo```, 17 sending ```c.move <- time.Now()```, and 47 receiving in database/sql.(*Tx).awaitDone.

Locks waiting:

gameListeningLock.RLock waiting to send diff: 40

gameMonitorsLock.Lock starting to listen for new game: 1

gameMonitorsLock.Lock after returning from listening: 6

gameMonitorsLock.Lock player not white or black (!): 5

gameListeningLock.Lock start of listeningToGame: 10

gameMonitorsLock.RLock notifying move: 1

**Comment by pciet** [comment]
Tx Begin() hang (26 goroutines):

```
goroutine 15636054 [select, 86 minutes]:
database/sql.(*DB).conn(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x1, 0x205, 0x0, 0x206)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1063 +0x62d
database/sql.(*DB).begin(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x0, 0x301, 0x0, 0x304, 0x0)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1566 +0x4f
database/sql.(*DB).BeginTx(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x0, 0x402, 0x0, 0x403)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1548 +0x8a
database/sql.(*DB).Begin(0xc4201b4000, 0x405, 0x0, 0x406)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1562 +0x4c
main.DB.Begin(0xc4201b4000, 0x0)
	/home/pciet/go/src/github.com/pciet/wichess/database.go:34 +0x2b
main.DB.updateGameTimes(0xc4201b4000, 0xd0d, 0xd18c2e2800, 0xc431ec1da8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pciet/go/src/github.com/pciet/wichess/game_time.go:91 +0x87
main.listeningToGame.func1(0xc4220013c0, 0x8, 0xc420b6ef60, 0xc420b6efc0, 0xd0d, 0xd18c2e2800, 0x321baad0, 0xed1f1a311, 0xc4233d21e0)
	/home/pciet/go/src/github.com/pciet/wichess/game_listening.go:94 +0x4ab
created by main.listeningToGame
	/home/pciet/go/src/github.com/pciet/wichess/game_listening.go:45 +0x52d
```

Database loading session info hang 1.5 hours after initial hang, triggered manually:

```
goroutine 15753300 [select, 3 minutes]:
database/sql.(*DB).conn(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x1, 0xc4204b8c00, 0xc40000006b, 0x7f46ca258000)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1063 +0x62d
database/sql.(*DB).query(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x85817a, 0x27, 0xc4210ef9c8, 0x1, 0x1, 0x687401, 0x7c5ca0, ...)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1437 +0x66
database/sql.(*DB).QueryContext(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x85817a, 0x27, 0xc4210ef9c8, 0x1, 0x1, 0x10, 0xc4201ac190, ...)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1419 +0xd2
database/sql.(*DB).QueryRowContext(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x85817a, 0x27, 0xc4210ef9c8, 0x1, 0x1, 0xc4201ac190)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1520 +0x8d
database/sql.(*DB).QueryRow(0xc4201b4000, 0x85817a, 0x27, 0xc4210ef9c8, 0x1, 0x1, 0xc4210ef9c8)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1531 +0x7c
main.DB.validSession(0xc4201b4000, 0xc42f336200, 0xc4262f0301, 0x9700000000000001, 0xe, 0xc4210efb28)
	/home/pciet/go/src/github.com/pciet/wichess/session.go:31 +0xea
main.indexHandler(0x8a0b60, 0xc42f8f8380, 0xc42f336200)
	/home/pciet/go/src/github.com/pciet/wichess/web_index.go:50 +0xa2
net/http.HandlerFunc.ServeHTTP(0x865a50, 0x8a0b60, 0xc42f8f8380, 0xc42f336200)
	/home/pciet/sdk/go1.10beta2/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xa94c20, 0x8a0b60, 0xc42f8f8380, 0xc42f336200)
	/home/pciet/sdk/go1.10beta2/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc420190750, 0x8a0b60, 0xc42f8f8380, 0xc42f336200)
	/home/pciet/sdk/go1.10beta2/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4203f2820, 0x8a0f20, 0xc42041c580)
	/home/pciet/sdk/go1.10beta2/src/net/http/server.go:1830 +0x648
created by net/http.(*Server).Serve
	/home/pciet/sdk/go1.10beta2/src/net/http/server.go:2795 +0x27b
```

Hang on loading game info in updateGameTimes (9 goroutines):

```
goroutine 15573578 [IO wait, 86 minutes]:
internal/poll.runtime_pollWait(0x7f46ca139e68, 0x72, 0xc42055c990)
	/home/pciet/sdk/go1.10beta2/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42f83cf98, 0x72, 0xffffffffffffff00, 0x89e360, 0xa566d0)
	/home/pciet/sdk/go1.10beta2/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42f83cf98, 0xc4219b0000, 0x1000, 0x1000)
	/home/pciet/sdk/go1.10beta2/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42f83cf80, 0xc4219b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/pciet/sdk/go1.10beta2/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42f83cf80, 0xc4219b0000, 0x1000, 0x1000, 0x434c2c, 0xc420f93500, 0x300000002)
	/home/pciet/sdk/go1.10beta2/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42016a0a0, 0xc4219b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/pciet/sdk/go1.10beta2/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc4204f8cc0, 0xc420940b20, 0x5, 0x200, 0x42bd54, 0x865958, 0xc42055cb80)
	/home/pciet/sdk/go1.10beta2/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x89ce80, 0xc4204f8cc0, 0xc420940b20, 0x5, 0x200, 0x5, 0x411f09, 0xc42145a1e0, 0x20)
	/home/pciet/sdk/go1.10beta2/src/io/io.go:309 +0x86
io.ReadFull(0x89ce80, 0xc4204f8cc0, 0xc420940b20, 0x5, 0x200, 0x0, 0xc420044800, 0xce)
	/home/pciet/sdk/go1.10beta2/src/io/io.go:327 +0x58
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).recvMessage(0xc420940b00, 0xc42145a1e0, 0x7aa120, 0xc420940b01, 0xab2a38)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:947 +0xf3
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).recv1Buf(0xc420940b00, 0xc42145a1e0, 0xa)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:997 +0x39
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).recv1(0xc420940b00, 0xc42016a0a0, 0xc420940b20)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:1018 +0x7c
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).readBindResponse(0xc420940b00)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:1633 +0x2f
github.com/pciet/wichess/vendor/github.com/lib/pq.(*stmt).exec(0xc4203f2460, 0xc4241a0180, 0x1, 0x1)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:1270 +0x823
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).query(0xc420940b00, 0xc429f740c0, 0x30, 0xc4241a0180, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn.go:855 +0x2a1
github.com/pciet/wichess/vendor/github.com/lib/pq.(*conn).QueryContext(0xc420940b00, 0x8a0f60, 0xc4200200f0, 0xc429f740c0, 0x30, 0xc4227a4270, 0x1, 0x1, 0xc42007c000, 0xc42055cff0, ...)
	/home/pciet/go/src/github.com/pciet/wichess/vendor/github.com/lib/pq/conn_go18.go:21 +0x1c8
database/sql.ctxDriverQuery(0x8a0f60, 0xc4200200f0, 0x7f46ca1bc020, 0xc420940b00, 0x0, 0x0, 0xc429f740c0, 0x30, 0xc4227a4270, 0x1, ...)
	/home/pciet/sdk/go1.10beta2/src/database/sql/ctxutil.go:48 +0x235
database/sql.(*DB).queryDC.func1()
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1464 +0x1c5
database/sql.withLock(0x89ebc0, 0xc421963800, 0xc42055d240)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:3032 +0x63
database/sql.(*DB).queryDC(0xc4201b4000, 0x8a0f60, 0xc4200200f0, 0x8a0f20, 0xc42006e440, 0xc421963800, 0xc4241a0170, 0xc429f740c0, 0x30, 0xc42055ee58, ...)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:1459 +0x5e9
database/sql.(*Tx).QueryContext(0xc42dec8200, 0x8a0f60, 0xc4200200f0, 0xc429f740c0, 0x30, 0xc42055ee58, 0x1, 0x1, 0x30, 0x1, ...)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:2128 +0x113
database/sql.(*Tx).QueryRowContext(0xc42dec8200, 0x8a0f60, 0xc4200200f0, 0xc429f740c0, 0x30, 0xc42055ee58, 0x1, 0x1, 0x30)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:2143 +0x8d
database/sql.(*Tx).QueryRow(0xc42dec8200, 0xc429f740c0, 0x30, 0xc42055ee58, 0x1, 0x1, 0x1)
	/home/pciet/sdk/go1.10beta2/src/database/sql/sql.go:2154 +0x7c
main.TX.gameWithIdentifier(0xc42dec8200, 0xd07, 0xc42dec8201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pciet/go/src/github.com/pciet/wichess/game.go:144 +0x190
main.DB.updateGameTimes(0xc4201b4000, 0xd07, 0xd18c2e2800, 0xc422974db8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pciet/go/src/github.com/pciet/wichess/game_time.go:93 +0xdc
main.listeningToGame.func1(0xc421352050, 0x8, 0xc421fdcb40, 0xc421fdcde0, 0xd07, 0xd18c2e2800, 0xe4d7408, 0xed1f1a2a6, 0xc4218f50e0)
	/home/pciet/go/src/github.com/pciet/wichess/game_listening.go:94 +0x4ab
created by main.listeningToGame
	/home/pciet/go/src/github.com/pciet/wichess/game_listening.go:45 +0x52d
```

**Comment by pciet** [comment]
/var/log/postgresql-9.5-main.log shows a lot of

```unexpected EOF on client connection with an open transaction```

and one

```could not receive data from client: Connection reset by peer```

**Comment by pciet** [comment]
```
// awaitDone blocks until the context in Tx is canceled and rolls back
// the transaction if it's not already done.
func (tx *Tx) awaitDone() {
	// Wait for either the transaction to be committed or rolled
	// back, or for the associated context to be closed.
	<-tx.ctx.Done() // 47 goroutines are blocked here

	// Discard and close the connection used to ensure the
	// transaction is closed and the resources are released.  This
	// rollback does nothing if the transaction has already been
	// committed or rolled back.
	tx.rollback(true)
}
```

**Comment by pciet** [comment]
Increases the postgres max connection count to 200 didn't fix it. Deadlock after 3k games: https://gist.github.com/pciet/5ae0157528c8db08a196508061044552

**Comment by pciet** [comment]
Fixed in https://github.com/pciet/wichess/commit/d5b6f6aa1caa005dc40afd027b0ee99d89dcf85e

Verified through 11k games.
