### ISSUE TITLE
crash: failed to execute template: write: broken pipe

### ISSUE THREAD

**Issue by pciet** [pciet/wichess#6]
This may be a client issue that the server shouldn't crash on:

> 2017/10/31 11:44:14 http: panic serving [::1]:53361: failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:53361: write: broken pipe
goroutine 4415 [running]:
net/http.(*conn).serve.func1(0xc4204706e0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x13855a0, 0xc4201a7f60)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc42010ae70, 0x64)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:51 +0x63
main.executeWebTemplate(0x15c3fe0, 0xc4201322a0, 0x1418399, 0x12, 0x13dd320, 0xc42000aa00)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web.go:51 +0x244
main.competitive15Handler(0x15c3fe0, 0xc4201322a0, 0xc42000ae00)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_competitive15.go:118 +0x9d6
net/http.HandlerFunc.ServeHTTP(0x142aa20, 0x15c3fe0, 0xc4201322a0, 0xc42000ae00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x15f5980, 0x15c3fe0, 0xc4201322a0, 0xc42000ae00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420126000, 0x15c3fe0, 0xc4201322a0, 0xc42000ae00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204706e0, 0x15c4620, 0xc420014a80)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by pciet** [comment]
Error can be checked via syscall.EPIPE: https://stackoverflow.com/questions/11003692/filter-out-broken-pipe-errors

The automated client is requesting the page but shouldn't be closing the pipe prematurely:

```golang
const(
	server        = "http://localhost:8080"
	competitive15 = server + "/competitive15"
)
...
r, err = client.Get(competitive15)
if err != nil {
	panic(err.Error())
}
var gameid int
scanner := bufio.NewScanner(r.Body)
for scanner.Scan() {
	t := scanner.Text()
	if strings.Contains(t, "var game_id = ") {
		_, err = fmt.Sscanf(t, "	var game_id = %d", &gameid)
		if err != nil {
			panic(err.Error())
		}
		break
	}
}
err = scanner.Err()
if err != nil {
	panic(err.Error())
}
if gameid == 0 {
	panic("zero value game identifier")
}
err = r.Body.Close()
if err != nil {
	panic(err.Error())
}
...
```

**Comment by pciet** [comment]
Added this to the test client after breaking out of scanning:

```golang
// read out the rest of the connection
_, err = io.Copy(ioutil.Discard, r.Body)
if err != nil {
	panic(err.Error())
}
```

From https://stackoverflow.com/questions/24707083/how-to-discard-any-incoming-data-in-a-connection-in-go

and I've changed t.Execute to log instead of panic because this is an unavoidable client behavior.

**Comment by pciet** [comment]
Reading the rest of r.Body actually didn't fix this when running the test client:

> 2017/11/02 15:12:22 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57228: write: protocol wrong type for socket
2017/11/02 15:12:22 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57189: write: broken pipe
2017/11/02 15:12:22 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57226: write: broken pipe
2017/11/02 15:12:22 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57218: write: broken pipe
2017/11/02 15:12:22 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57225: write: broken pipe
2017/11/02 15:12:22 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57205: write: broken pipe
2017/11/02 15:12:23 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57236: write: broken pipe
2017/11/02 15:12:23 failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:57233: write: broken pipe

**Comment by pciet** [comment]
Changed template.Execute error to log instead of panic in https://github.com/pciet/wichess/commit/93258a725e970f3e6c3df817e12850a768d563e5

**Comment by pciet** [comment]
Should be fixed in https://github.com/pciet/wichess/commit/2c37f22785102a3acaf0a8019b7b28e5c3b0eabf by reading out the body in every case from the clients. Hasn't been seen in a couple of hours of concurrent testing.
