### ISSUE TITLE
crash: failed to execute template: write: protocol wrong type for socket

### ISSUE THREAD

**Issue by pciet** [pciet/wichess#7]
When running wichess/test:

> 2017/10/31 12:53:58 http: panic serving [::1]:51285: failed to execute template web/html/game.html: write tcp [::1]:8080->[::1]:51285: write: protocol wrong type for socket
goroutine 179 [running]:
net/http.(*conn).serve.func1(0xc4201ea6e0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1385ea0, 0xc4204cf6e0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc420070580, 0x77)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:51 +0x63
main.executeWebTemplate(0x15c4fe0, 0xc420132620, 0x1418cb9, 0x12, 0x13ddc40, 0xc420130600)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web.go:51 +0x244
main.competitive15Handler(0x15c4fe0, 0xc420132620, 0xc420130e00)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_competitive15.go:114 +0x9bf
net/http.HandlerFunc.ServeHTTP(0x142b340, 0x15c4fe0, 0xc420132620, 0xc420130e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x15f6980, 0x15c4fe0, 0xc420132620, 0xc420130e00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420126000, 0x15c4fe0, 0xc420132620, 0xc420130e00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201ea6e0, 0x15c5620, 0xc420209140)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by pciet** [comment]
Duplicate of https://github.com/pciet/wichess/issues/6
