### ISSUE TITLE
dial tcp: lookup localhost: no such host

### ISSUE THREAD

**Issue by pciet** [pciet/wichess#9]
Crash after playing just over 100 games with 20 concurrent clients (wichess/test):

>2017/11/06 15:57:40 http: panic serving [::1]:61396: dial tcp: lookup localhost: no such host
goroutine 481486 [running]:
net/http.(*conn).serve.func1(0xc4204b4460)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x13937a0, 0xc4204ee800)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc42041de30, 0x28)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:51 +0x63
main.DB.playersCompetitive5HourGameID(0xc420077220, 0xc42042f6b5, 0x8, 0x8)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/player.go:53 +0x17b
main.movesHandler(0x15db1c0, 0xc420346700, 0xc42000bc00)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_moves.go:39 +0x1b5
net/http.HandlerFunc.ServeHTTP(0x143b778, 0x15db1c0, 0xc420346700, 0xc42000bc00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x160d860, 0x15db1c0, 0xc420346700, 0xc42000bc00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200aed10, 0x15db1c0, 0xc420346700, 0xc42000bc00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204b4460, 0x15db800, 0xc42022cb00)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

This is on the database query, not the http request handling. Running on macOS, connections being leaked? The client calls response.Body.Close() on every request.

https://stackoverflow.com/questions/26228163/localhost-no-such-host-after-250-connections-in-go-when-using-responsewriter

**Comment by pciet** [comment]
Could be rows not being closed: https://github.com/lib/pq/issues/550

**Comment by pciet** [comment]
A database/sql example uses the QueryRow(...).Scan(...) pattern without closing the row:

```golang
func ExampleDB_QueryRow() {
  	id := 123
  	var username string
  	err := db.QueryRow("SELECT username FROM users WHERE id=?", id).Scan(&username)
  	switch {
  	case err == sql.ErrNoRows:
  		log.Printf("No user with that ID.")
  	case err != nil:
  		log.Fatal(err)
  	default:
  		fmt.Printf("Username is %s\n", username)
  	}
  }
```

https://golang.org/src/database/sql/example_test.go

**Comment by pciet** [comment]
https://github.com/golang/go/issues/17295

>nussjustin commented on Sep 30, 2016
QueryRow, like the Query and Exec methods, does not close connections, but puts them back into a connection pool once you are done with the result (in the case of QueryRow, this means calling the Scan method on the result Row). Other queries can than use a connection from the pool, if there is any, to avoid creating new connections (which can take some time). See the documentation for sql.DB.You can limit the number of idle connections in the pool by using SetMaxIdleConns, limit the maximum number of open connections with SetMaxOpenConns and use SetConnMaxLifetime to limit the lifetime of connections (note that this method does not guarantee that connections are closed immediately).
--

**Comment by pciet** [comment]
Using Activity Monitor.app I can see that the number of open network connections quickly gets into the 200 range when testing 100 concurrent clients:

<img width="547" alt="screen shot 2017-11-06 at 5 42 59 pm" src="https://user-images.githubusercontent.com/7949131/32469816-09b6673a-c31a-11e7-871f-6faa1bbf3666.png">

The number was at 256 when I saw the crash this last time which matches what I've read about macOS fd limits.

**Comment by pciet** [comment]
https://github.com/golang/go/issues/6785

The number of open connections is dependent on the server load - my client test load may be unrealistic given the two-core contention between 100 concurrent clients / the server / the database or represent a case that requires multiple instances anyway.

It seems like the number of open files increases depending on other system loads - it may be the number of client requests pile up to a point where the http stack can no longer accept new requests because of exhausted fd's.

This crash has a different error message but seemed to trigger when Activity Monitor showed it growing to 256.

>2017/11/06 18:13:02 http: panic serving [::1]:55717: dial tcp [::1]:5432: socket: too many open files
goroutine 3491 [running]:
net/http.(*conn).serve.func1(0xc420378500)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1392c40, 0xc4204a5a90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.panicExit(0xc4202e06f0, 0x30)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/main.go:58 +0x63
main.DB.playersFreePieces(0xc420081180, 0xc42046b115, 0x8, 0x0, 0x0, 0x0)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/piece.go:97 +0x48a
main.freePiecesHandler(0x15da200, 0xc420502460, 0xc420a8a100)
	/Users/aftermatt/Code/src/github.com/pciet/wichess/web_piece.go:27 +0xd3
net/http.HandlerFunc.ServeHTTP(0x143aa00, 0x15da200, 0xc420502460, 0xc420a8a100)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x160c8a0, 0x15da200, 0xc420502460, 0xc420a8a100)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200bcbb0, 0x15da200, 0xc420502460, 0xc420a8a100)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420378500, 0x15da840, 0xc420014d40)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by pciet** [comment]
The gorilla/websocket dialer uses net.Dial which disables keep-alive by default, so if the websockets are being closed there should be no connection leaks there. 

gorilla/websocket:

```golang
// A Dialer contains options for connecting to WebSocket server.
type Dialer struct {
    // NetDial specifies the dial function for creating TCP connections. If
    // NetDial is nil, net.Dial is used.
    NetDial func(network, addr string) (net.Conn, error)
```

net:

```golang
// The zero value for each field is equivalent to dialing without that option. 
// Dialing with the zero value of Dialer is therefore equivalent to just calling the Dial function.
type Dialer struct {
...
        // KeepAlive specifies the keep-alive period for an active
        // network connection.
        // If zero, keep-alives are not enabled. Network protocols
        // that do not support keep-alives ignore this field.
        KeepAlive time.Duration
```

gorilla/websocket:

```golang
func (d *Dialer) Dial(urlStr string, requestHeader http.Header) (*Conn, *http.Response, error) {
...
	netDial := d.NetDial
	if netDial == nil {
		netDialer := &net.Dialer{Deadline: deadline}
		netDial = netDialer.Dial
	}
	netConn, err := netDial("tcp", targetHostPort)
	if err != nil {
		return nil, nil, err
	}
```

On the server websocket.Upgrader has no options for connection pooling.

**Comment by pciet** [comment]
The server was not closing the websockets due to an early return in the monitoring goroutine, fixed in https://github.com/pciet/wichess/commit/2c37f22785102a3acaf0a8019b7b28e5c3b0eabf - after 200-300 games with 100 or 20 concurrent clients I haven't seen this crash and Activity Monitor shows a somewhat stable fd number. This commit also sets idle connection limits for sql and http.
